package clustersapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/clusters"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            Create(ctx context.Context, body clusters.Attributes) (result clusters.CreateResult, err error)
            Delete(ctx context.Context, body clusters.DeleteAttributes) (result autorest.Response, err error)
            Edit(ctx context.Context, body clusters.EditAttributes) (result autorest.Response, err error)
            Get(ctx context.Context, clusterID string) (result clusters.Info, err error)
            List(ctx context.Context) (result clusters.ListInfo, err error)
            ListNodeTypes(ctx context.Context) (result clusters.ListNodeType, err error)
            PermanentDelete(ctx context.Context, body clusters.PermanentDeleteAttributes) (result autorest.Response, err error)
            Resize(ctx context.Context, body clusters.ResizeAttributes) (result autorest.Response, err error)
            Restart(ctx context.Context, body clusters.RestartAttributes) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*clusters.BaseClient)(nil)
