package dbfs

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

// The package's fully qualified name.
const fqdn = "github.com/innovationnorway/go-databricks/dbfs"

            // DeleteAttributes ...
            type DeleteAttributes struct {
            Path *string `json:"path,omitempty"`
            Recursive *bool `json:"recursive,omitempty"`
            }

            // GetStatusResult ...
            type GetStatusResult struct {
            autorest.Response `json:"-"`
            Path *string `json:"path,omitempty"`
            IsDir *bool `json:"is_dir,omitempty"`
            FileSize *int64 `json:"file_size,omitempty"`
            }

            // MkdirsAttributes ...
            type MkdirsAttributes struct {
            Path *string `json:"path,omitempty"`
            }

            // PutAttributes ...
            type PutAttributes struct {
            Path *string `json:"path,omitempty"`
            Contents *string `json:"contents,omitempty"`
            Overwrite *bool `json:"overwrite,omitempty"`
            }

