package groupsapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/groups"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            AddMember(ctx context.Context, body groups.MemberAttributes) (result autorest.Response, err error)
            Create(ctx context.Context, body groups.Attributes) (result groups.CreateResult, err error)
            Delete(ctx context.Context, body groups.DeleteAttributes) (result autorest.Response, err error)
            List(ctx context.Context) (result groups.ListListResult, err error)
            ListMembers(ctx context.Context, groupName string) (result groups.ListMembersResult, err error)
            ListParents(ctx context.Context, groupName string, userName string) (result groups.ListListResult, err error)
            RemoveMember(ctx context.Context, body groups.MemberAttributes) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*groups.BaseClient)(nil)
