package workspaceapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/workspace"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            Delete(ctx context.Context, body workspace.DeleteAttributes) (result autorest.Response, err error)
            Export(ctx context.Context, pathParameter string, formatParameter string, directDownload *bool) (result workspace.ExportResult, err error)
            GetStatus(ctx context.Context, pathParameter string) (result workspace.ObjectInfo, err error)
            Import(ctx context.Context, body workspace.ImportAttributes) (result autorest.Response, err error)
            List(ctx context.Context, pathParameter string) (result workspace.ListResult, err error)
            Mkdirs(ctx context.Context, body workspace.MkdirsAttributes) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*workspace.BaseClient)(nil)
