package secretsapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/innovationnorway/go-databricks/secrets"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            AclsDelete(ctx context.Context, body secrets.AclsRequest) (result autorest.Response, err error)
            AclsGet(ctx context.Context, body secrets.AclsRequest) (result secrets.AclsResult, err error)
            AclsList(ctx context.Context, body secrets.ListSecretsAclsRequest) (result secrets.ListSecretsAclsResult, err error)
            AclsPut(ctx context.Context, body secrets.PutSecretACLRequest) (result autorest.Response, err error)
            CreateScope(ctx context.Context, body secrets.CreateScopeRequest) (result autorest.Response, err error)
            Delete(ctx context.Context, body secrets.Request) (result autorest.Response, err error)
            DeleteScope(ctx context.Context, body secrets.DeleteScopeRequest) (result autorest.Response, err error)
            List(ctx context.Context, body secrets.ListSecretsRequest) (result secrets.ListResult, err error)
            ListScopes(ctx context.Context) (result secrets.ListScopesResult, err error)
            Put(ctx context.Context, body secrets.Request) (result autorest.Response, err error)
        }

        var _ BaseClientAPI = (*secrets.BaseClient)(nil)
