package workspace

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

// The package's fully qualified name.
const fqdn = "github.com/innovationnorway/go-databricks/workspace"

        // Format enumerates the values for format.
    type Format string

    const (
                // DBC ...
        DBC Format = "DBC"
                // HTML ...
        HTML Format = "HTML"
                // JUPYTER ...
        JUPYTER Format = "JUPYTER"
                // SOURCE ...
        SOURCE Format = "SOURCE"
            )
    // PossibleFormatValues returns an array of possible values for the Format const type.
    func PossibleFormatValues() []Format {
        return []Format{DBC,HTML,JUPYTER,SOURCE}
    }

        // Format1 enumerates the values for format 1.
    type Format1 string

    const (
                // Format1DBC ...
        Format1DBC Format1 = "DBC"
                // Format1HTML ...
        Format1HTML Format1 = "HTML"
                // Format1JUPYTER ...
        Format1JUPYTER Format1 = "JUPYTER"
                // Format1SOURCE ...
        Format1SOURCE Format1 = "SOURCE"
            )
    // PossibleFormat1Values returns an array of possible values for the Format1 const type.
    func PossibleFormat1Values() []Format1 {
        return []Format1{Format1DBC,Format1HTML,Format1JUPYTER,Format1SOURCE}
    }

        // Language enumerates the values for language.
    type Language string

    const (
                // PYTHON ...
        PYTHON Language = "PYTHON"
                // R ...
        R Language = "R"
                // SCALA ...
        SCALA Language = "SCALA"
                // SQL ...
        SQL Language = "SQL"
            )
    // PossibleLanguageValues returns an array of possible values for the Language const type.
    func PossibleLanguageValues() []Language {
        return []Language{PYTHON,R,SCALA,SQL}
    }

        // Language1 enumerates the values for language 1.
    type Language1 string

    const (
                // Language1PYTHON ...
        Language1PYTHON Language1 = "PYTHON"
                // Language1R ...
        Language1R Language1 = "R"
                // Language1SCALA ...
        Language1SCALA Language1 = "SCALA"
                // Language1SQL ...
        Language1SQL Language1 = "SQL"
            )
    // PossibleLanguage1Values returns an array of possible values for the Language1 const type.
    func PossibleLanguage1Values() []Language1 {
        return []Language1{Language1PYTHON,Language1R,Language1SCALA,Language1SQL}
    }

        // ObjectType enumerates the values for object type.
    type ObjectType string

    const (
                // DIRECTORY ...
        DIRECTORY ObjectType = "DIRECTORY"
                // LIBRARY ...
        LIBRARY ObjectType = "LIBRARY"
                // NOTEBOOK ...
        NOTEBOOK ObjectType = "NOTEBOOK"
            )
    // PossibleObjectTypeValues returns an array of possible values for the ObjectType const type.
    func PossibleObjectTypeValues() []ObjectType {
        return []ObjectType{DIRECTORY,LIBRARY,NOTEBOOK}
    }

            // DeleteAttributes ...
            type DeleteAttributes struct {
            Path *string `json:"path,omitempty"`
            Recursive *bool `json:"recursive,omitempty"`
            }

            // ExportAttributes ...
            type ExportAttributes struct {
            Path *string `json:"path,omitempty"`
            // Format - Possible values include: 'SOURCE', 'HTML', 'JUPYTER', 'DBC'
            Format Format `json:"format,omitempty"`
            DirectDownload *bool `json:"direct_download,omitempty"`
            }

            // ExportResult ...
            type ExportResult struct {
            autorest.Response `json:"-"`
            Content *[]byte `json:"content,omitempty"`
            }

            // ImportAttributes ...
            type ImportAttributes struct {
            Path *string `json:"path,omitempty"`
            // Format - Possible values include: 'Format1SOURCE', 'Format1HTML', 'Format1JUPYTER', 'Format1DBC'
            Format Format1 `json:"format,omitempty"`
            // Language - Possible values include: 'Language1SCALA', 'Language1PYTHON', 'Language1SQL', 'Language1R'
            Language Language1 `json:"language,omitempty"`
            Content *[]byte `json:"content,omitempty"`
            Overwrite *bool `json:"overwrite,omitempty"`
            }

            // ListResult ...
            type ListResult struct {
            autorest.Response `json:"-"`
            Objects *[]ObjectInfo `json:"objects,omitempty"`
            }

            // MkdirsAttributes ...
            type MkdirsAttributes struct {
            Path *string `json:"path,omitempty"`
            }

            // ObjectInfo ...
            type ObjectInfo struct {
            autorest.Response `json:"-"`
            // ObjectType - Possible values include: 'NOTEBOOK', 'DIRECTORY', 'LIBRARY'
            ObjectType ObjectType `json:"object_type,omitempty"`
            ObjectID *int64 `json:"object_id,omitempty"`
            Path *string `json:"path,omitempty"`
            // Language - Possible values include: 'SCALA', 'PYTHON', 'SQL', 'R'
            Language Language `json:"language,omitempty"`
            }

